services:
  db:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME?}
      POSTGRES_USER: ${DB_USER?}
      POSTGRES_PASSWORD: ${DB_PASSWORD?}

  storybook:
    image: arthureudeline/starbucks-tp-kit-storybook:2.0
    ports: 
      - 6006:80